
# Normal list generation for odd numbers

l1 = []
for i in range(10):
    if i%3==0:
        l1.append(i)

print("This list is generated by for loop: %s"%(l1))

# Above code in one liner provided below

# List comprehension: with single IF condition
l2 = [i for i in range(10) if i%3 == 0]
print("\nodd number list: %s"%l2)

# List comprehension: IF and ELSE condition
l3 = [True if i%2==0 else False for i in range(10)]

# List comprehension: Multiple FOR loops
l4 = [i+j for i in range(2) for j in range(5)]
print("\nMultiple for loop list: %s"%l4)


# Dict comprehensions

# Basic dict comprehension: key and its square
d1 = {k:k*k for k in range(10)}
print("\nBasic dict comprehension: %s"%d1)

# Dict comprehension: with single IF
d2 = {k:'is even' for k,v in zip(range(10), range(10)) if k%2==0}
print("\nEven key dict: %s"%d2)

# Dict comprehension: with IF and ESLE
d3 = {k:True if k%3==0 else False for k in range(20)}
print("\nOdd value dict: %s"%d3)
